name: Swift Setup
description: Setup the environment for Swift development

inputs:
  swift-version:
    description: "Swift version to set up"
    required: true

runs:
  using: "composite"
  steps:
    - name: Runner OS ==> '${{ runner.os }}'"
      shell: bash
      run: echo "'${{ runner.os }}'"
    - name: Pull Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ inputs.swift-version }}
    - name: Swift Version
      shell: bash
      run: swift --version
    - name: Install SwiftLint ['macOS']
      if: runner.os == 'macOS'
      shell: bash
      run: brew install swiftlint 2>/dev/null && true
    - name: SwiftLint Version
      if: runner.os == 'macOS'
      shell: bash
      run: swiftlint --version
