name: 🛠️

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main, feature/**, fix/**, ci/**]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

jobs:
  Build:
    runs-on: macos-15
    steps:
      - name: Swift Setup
        uses: ./.github/actions/swift-setup
      - name: SwiftLint
        run: swiftlint lint --strict
      - name: Build
        run: swift build

  Test:
    runs-on: macos-15
    needs: Build
    steps:
      - name: Swift Setup
        uses: ./.github/actions/swift-setup
      - name: Test
        run: swift test --enable-code-coverage
      - name: Code Coverage
        uses: drekka/swift-coverage-action@v1
        with:
          coverage: 90
