name: 🛠️

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main, feature/**, fix/**, ci/**, docs/**, misc/**]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

jobs:
  package-build:
    name: Build - Test - Coverage | swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        swift-version: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup Swift
        uses: ./.github/actions/swift-setup
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: SwiftLint
        run: swiftlint lint --strict
      - name: Build (for swift ${{ matrix.swift-version }})
        run: swift build
      - name: Test (for swift ${{ matrix.swift-version }})
        run: swift test --enable-code-coverage
      - name: Code Coverage
        uses: drekka/swift-coverage-action@v1
        with:
          coverage: 90
