name: 🛠️ Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main, feature/**, fix/**, ci/**, docs/**, misc/**]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-24.04]
        swift-version: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Swift Setup
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Build (for swift ${{ matrix.swift-version }})
        run: swift build
