name: 💡 Lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    branches: [main, feature/**, fix/**, ci/**, docs/**, misc/**]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [macos-15]
        swift-version: ["6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Swift Setup
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Install SwiftLint
        shell: bash
        run: brew install swiftlint 2>/dev/null && true
      - name: SwiftLint Version
        run: swiftlint --version
      - name: Lint
        run: swiftlint lint --strict
